// Thermostat peripheral main file.
// Uses averclock for super duper clocky goodness, created
// by @naggie on github.
// Copyright, where applicable, James Reuss 2013.
// Created 22 March 2013.

// TODO lots

// this is automatically generated by deploy.sh
#include "../config.h"
//#include "current_time.h" // to be done correctly shortly. for now...
#include "some_time.h"
#include "time.h"
#include "thermometer.h"
#include "schavr.h"
//#include "display.h"
//#include "remote.h"

void setup()
{
	// Setup scheduler
	SCH_init(50);	// 50ms per tick
	
	// Initialise everything we need
	heartbeat_init();
	
	// Setup timing for scheduler
	SCH_add_task(time_inc_sec, 1, 20);		//50ms * 20ticks = 1000ms
	SCH_add_task(heartbeat_flash, 2, 10);		//50ms * 10ticks = 500ms
	
	// Let's go
	SCH_start();
}

void loop()
{
	SCH_dispatch_tasks();
}
