// Thermostat peripheral main file.
// Uses averclock for super duper clocky goodness, created
// by @naggie on github.
// Copyright, where applicable, James Reuss 2013.
// Created 22 March 2013.

// TODO lots

// this is automatically generated by deploy.sh
#include "../config.h"
#include "current_time.h" // the current time as of upload
#include "time.h"
#include "thermometer.h"
#include "schavr.h"
#include "lcd.h"
//#include "remote.h"

void setup()
{
	// Setup scheduler
	SCH_init(200);	// 200ms per tick
	
	// Initialise everything we need
	thermometer_init();
	lcd_init();
	
	// Setup timing for scheduler
	SCH_add_task(time_inc_sec, 1, 5);		//200ms * 5ticks = 1000ms
	SCH_add_task(thermometer_update, 2, 5);	//200ms * 5ticks = 1000ms
	SCH_add_task(thermometer_serial_print, 3, 10);	//200ms * 10ticks = 2000ms
	SCH_add_task(lcd_update, 4, 25);	//200ms * 25ticks = 5000ms
	
	// Let's go
	SCH_start();
}

void loop()
{
	SCH_dispatch_tasks();
}
